version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_microfinance_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"
    networks:
      - microfinance-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=microfinance_db
      - DB_USERNAME=microfinance_user
      - DB_PASSWORD=microfinance_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: laravel_microfinance_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: microfinance_db
      MYSQL_USER: microfinance_user
      MYSQL_PASSWORD: microfinance_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microfinance-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: laravel_microfinance_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microfinance-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: laravel_microfinance_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microfinance-network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_microfinance_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: microfinance_user
      PMA_PASSWORD: microfinance_password
    networks:
      - microfinance-network
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: laravel_microfinance_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: redis:redis:6379
    networks:
      - microfinance-network
    depends_on:
      - redis

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  microfinance-network:
    driver: bridge